services:
  twitch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitch
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - twitch-data:/data
    environment:
      - LOG_LEVEL
      - SERVER_PORT=8081
      - DB_PATH=/data/charsibot.db
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - TWITCH_OAUTH_TOKEN
      - TWITCH_REFRESH_TOKEN
      - TWITCH_BOT_OAUTH_TOKEN
      - TWITCH_BOT_REFRESH_TOKEN
      - TWITCH_BOT_USER_ID
      - TWITCH_CHANNEL_USER_ID

volumes:
  twitch-data:
    external: true
